#!/bin/bash

# Prepare output directories
#mkdir spliced

# Clean up the image
convert `current` -resize x1200 processed/`current`
textcleaner -c 0,72,0,36 -g -e stretch -f 20 -o 20 -t 30 -u -s 0 -T -p 20 spliced/$1 spliced/$1

# Trim it from all sides
autotrim -f 80 -p vo split/`current` processed/`current`

# Cut into 2 equal columns
convert processed/`current` -crop 50%x100% split/`current`_%d.png

# Now cut the individual columns into individual questions
mkdir spliced/ques
ind_cut split/caps_103.png_1.png -o spliced -b 10x20 -m 5
